# coding:utf-8

IMAGE_CODE_EXPIRES_SECONDS = 120 # 图片验证码有效时间 单位：秒
SMS_CODE_EXPIRES_SECONDS = 300 # 短信验证码有效时间 单位：秒
AREA_INFO_REDIS_EXPIRES_SECONDS = 86400 # 区域信息缓存时间 单位：秒
MYHOUSES_INFO_REDIS_EXPIRES_SECONDS = 86400 # 个人信息缓存时间 单位：秒

HOUSE_LIST_PAGE_CAPACITY = 3 # 房屋列表每页数量
HOUSE_LIST_REDIS_CACHED_PAGE = 2 # REDIS每次缓存的房屋列表页数
HOUSE_LIST_REDIS_EXPIRES_SECONDS = 3600 # 房屋列表缓存时间
